name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  sprint_1:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: 小heck if the repository is private
      run: exit 1
      if: ${{github.event.repository.private}}
    - name: Get testing lib
      run: set -eu && git clone -b refactor --single-branch https://github.com/rpill/tests-second-floor.git
    - name: Run the tests 
      run: bash tests-second-floor/bin/sprint-1.sh
      
  sprint_2:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: 小heck if the repository is private
      run: exit 1
      if: ${{github.event.repository.private}}
    - name: Get testing lib
      run: set -eu && git clone -b refactor --single-branch https://github.com/rpill/tests-second-floor.git
    - name: Run the tests 
      run: bash tests-second-floor/bin/sprint-2.sh
      
  sprint_3:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: 小heck if the repository is private
      run: exit 1
      if: ${{github.event.repository.private}}
    - name: Get testing lib
      run: set -eu && git clone -b refactor --single-branch https://github.com/rpill/tests-second-floor.git
    - name: Run the tests 
      run: bash tests-second-floor/bin/sprint-3.sh
      
  sprint_4:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: 小heck if the repository is private
      run: exit 1
      if: ${{github.event.repository.private}}
    - name: Get testing lib
      run: set -eu && git clone -b refactor --single-branch https://github.com/rpill/tests-second-floor.git
    - name: Run the tests 
      run: bash tests-second-floor/bin/sprint-4.sh
